### ISSUE TITLE
"Limit Oversized Node Render" inconsistent between locations

### ISSUE THREAD

**Issue by truenachtara** [Glease/TC4Tweaks#14]
## Mod Version
1.3.1

## Describe the bug
Nodes are still massive in certain locations:
Ethereal Shards
Jarred Nodes as items
As an actual, non-energized node

## To Reproduce
1. Make bigass node
2. Use it like you would use a node

## Expected behavior
All things that render glow based on vis stored have limited size

## Screenshots/Screencast
![image](https://user-images.githubusercontent.com/16340367/121966959-230dcd80-cd35-11eb-9e93-19c7d3e3f236.png)
![image](https://user-images.githubusercontent.com/16340367/121967132-708a3a80-cd35-11eb-867f-d0b03b225000.png)
![image](https://user-images.githubusercontent.com/16340367/121967145-7aac3900-cd35-11eb-9aa0-c7766e2c4ee1.png)
![image](https://user-images.githubusercontent.com/16340367/121967245-a5968d00-cd35-11eb-843b-a1f495144c88.png)
![image](https://user-images.githubusercontent.com/16340367/121967343-cbbc2d00-cd35-11eb-9574-f1b221e932cd.png)
(Node has limited size once energized)

**Comment by Glease** [comment]
Should be fixed with 1.3.2. https://www.curseforge.com/minecraft/mc-mods/tc4tweaks/files/3352429

![node in a jar in world](https://user-images.githubusercontent.com/4586901/121978358-99084800-cdba-11eb-820e-8725ee7dd48c.png)
![node](https://user-images.githubusercontent.com/4586901/121978361-9ad20b80-cdba-11eb-9b74-f6d1a86d5f7f.png)
![node in a jar in inventory](https://user-images.githubusercontent.com/4586901/121978362-9b6aa200-cdba-11eb-8b1f-c4d942eac89c.png)

**Comment by truenachtara** [comment]
![image](https://user-images.githubusercontent.com/16340367/122307557-330de480-ced0-11eb-877e-ace5c034403c.png)

Missed a spot.

**Comment by Glease** [comment]
How big is that node and what node is that? In my tests (a 32000 sized terra node) normal nodes are also rendered with a limited size.

**Comment by truenachtara** [comment]
It's 1667 Tempestas, and it was previously energized but I de-energized it and let it recover.

**Comment by Glease** [comment]
Seems to be an incompatibility with gadomancy. Will see what I can do.

**Comment by Glease** [comment]
Fixed in 1.3.4.
